force-app/main/default/objects/Authorization_Details__c/Authorization_Details__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Save user name and access token</description>
    <label>Authorization Details</label>
</CustomObject>

force-app/main/default/objects/Credentials__c/Credentials__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Credentials</description>
    <label>Credentials</label>
</CustomObject>

force-app/main/default/objects/Credentials__c/fields/Consumer_Key_Auto__c.field-meta.xml
<CustomField>
    <fullName>Consumer_Key_Auto__c</fullName>
    <label>Consumer Key(Auto)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credentials__c/fields/Consumer_Secret_Auto__c.field-meta.xml
<CustomField>
    <fullName>Consumer_Secret_Auto__c</fullName>
    <label>Consumer Secret(Auto)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credentials__c/fields/ConsumerKey__c.field-meta.xml
<CustomField>
    <fullName>ConsumerKey__c</fullName>
    <label>Consumer Key(Manual)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Credentials__c/fields/ConsumerSecret__c.field-meta.xml
<CustomField>
    <fullName>ConsumerSecret__c</fullName>
    <label>Consumer Secret(Manual)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Organisation__c/Organisation__c.object-meta.xml
<CustomObject>
    <label>Org</label>
    <nameField>
        <label>Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orgs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Organisation__c/fields/Username__c.field-meta.xml
<CustomField>
    <fullName>Username__c</fullName>
    <label>Username</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AuthUtilsTest.cls
@isTest
private class AuthUtilsTest {
    static testMethod void myUnitTest() {
        Credentials__c cred = new Credentials__c(
            ConsumerSecret__c = '123456987',
            Redirect_URL__c = '001',
            Consumer_Key_Auto__c = 'key',
            Consumer_Secret_Auto__c = 'secret',
            ConsumerKey__c = '1234569874563214569513578264'
        );
        insert cred;
        Authorization_Details__c auth = new Authorization_Details__c(
            AuthorisedUser__c = 'test@testOrg.com',
            Name = 'test@testOrg.com',
            AccessToken__c = 'test',
            RefreshToken__c = 'test',
            InstanceURL__c = 'test'
        );
        insert auth;

        Organisation__c org = new Organisation__c(Username__c = 'test@testOrg.com', Name = 'Test12345678@testorg.com');
        insert org;

        Test.startTest();
        Map<Id, AuthUtils.CredDetails> orgsCreds = AuthUtils.getListDefaultCreds(new List<String>{ org.Id });
        AuthUtils.authenticateAnOrg(org.Id, 'test@testOrg.com', FlosumConstants.DEVELOPER, orgsCreds.get(org.Id));
        AuthUtils.authenticateAnOrg(org.Id, 'test@testOrg.com', FlosumConstants.RELEASE_MANAGER, orgsCreds.get(org.Id));
        AuthUtils.authenticateAnOrg(org.Id, 'test@testOrg.com', FlosumConstants.VALIDATE_ONLY, orgsCreds.get(org.Id));
        AuthUtils.authenticateAnOrg(org.Id, FlosumConstants.DEVELOPER);
        AuthUtils.authenticateAnOrg(org.Id, FlosumConstants.RELEASE_MANAGER);
        AuthUtils.authenticateAnOrg(org.Id, FlosumConstants.READONLY);
        AuthUtils.authenticateAnOrg(org.Id, FlosumConstants.VALIDATE_ONLY);
        AuthUtils.authenticateAnOrg(org.Id, FlosumConstants.AUDIT_ONLY);
        AuthUtils.authenticateAnOrg(org.Id, null);
        Test.stopTest();
        System.assertNotEquals(cred.Id, null);
    }

    static testMethod void myUnitTest1() {
        Credentials__c cred = new Credentials__c(
            ConsumerSecret__c = '123456987',
            Redirect_URL__c = '001',
            Consumer_Key_Auto__c = 'key',
            Consumer_Secret_Auto__c = 'secret',
            ConsumerKey__c = '1234569874563214569513578264'
        );
        insert cred;
        Test.startTest();
        AuthUtils.getValue(null, 'key');
        Test.stopTest();
        System.assertNotEquals(cred.Id, null);
    }
}