force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Branch Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch Lookup</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Branch__c.RecordType.Id</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <infoMessage>Select a record type</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Branches</relationshipLabel>
    <relationshipName>Branches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Branch__c/fields/Branch_Name__c.field-meta.xml
<CustomField>
    <fullName>Branch_Name__c</fullName>
    <label>Branch Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branch__c/fields/Repository__c.field-meta.xml
<CustomField>
    <fullName>Repository__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Repository</label>
    <referenceTo>Repository__c</referenceTo>
    <relationshipLabel>Branches</relationshipLabel>
    <relationshipName>Branches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Branch__c/fields/Repository_Type__c.field-meta.xml
<CustomField>
    <fullName>Repository_Type__c</fullName>
    <formula>TEXT(Repository__r.Repository_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Repository Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branch__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Metadata_Log__c/Metadata_Log__c.object-meta.xml
<CustomObject>
    <label>Metadata Log</label>
    <nameField>
        <displayFormat>ML-{YYYY}-{MM}-{DD}-{0000}</displayFormat>
        <label>Metadata Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metadata Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Metadata_Log__c/fields/Async_Request_Id__c.field-meta.xml
<CustomField>
    <fullName>Async_Request_Id__c</fullName>
    <description>Id of the retrieval or deployment request sent to Salesforce organisation</description>
    <label>Deployment Request Id</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Metadata_Log__c/fields/Automation_Completed__c.field-meta.xml
<CustomField>
    <fullName>Automation_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Automation Completed?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Metadata_Log__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Metadata Logs</relationshipLabel>
    <relationshipName>Metadata_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Metadata_Log__c/fields/Error_Log__c.field-meta.xml
<CustomField>
    <fullName>Error_Log__c</fullName>
    <label>Error Log</label>
    <length>32001</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Metadata_Log__c/fields/Job_Completed__c.field-meta.xml
<CustomField>
    <fullName>Job_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Show if the process related to deployment or retrieve has been completed or not for the current  Async request Id</description>
    <label>Job Completed?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Metadata_Log__c/fields/Metadata_Types__c.field-meta.xml
<CustomField>
    <fullName>Metadata_Types__c</fullName>
    <label>Metadata Types</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Metadata_Log__c/fields/Options__c.field-meta.xml
<CustomField>
    <fullName>Options__c</fullName>
    <description>Other options for deployment/validation</description>
    <label>Options</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Metadata_Log__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization</label>
    <referenceTo>Organisation__c</referenceTo>
    <relationshipLabel>Metadata Logs</relationshipLabel>
    <relationshipName>Metadata_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Metadata_Log__c/fields/PipelineStepId__c.field-meta.xml
<CustomField>
    <fullName>PipelineStepId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PipelineStepId</label>
    <referenceTo>PipelineStep__c</referenceTo>
    <relationshipLabel>Metadata Logs</relationshipLabel>
    <relationshipName>Metadata_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Metadata_Log__c/fields/Process_Type__c.field-meta.xml
<CustomField>
    <fullName>Process_Type__c</fullName>
    <description>Determine the process for which the log has been created</description>
    <label>Process Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Patch</fullName>
                <color>#0B6FCE</color>
                <label>Patch</label>
            </value>
            <value>
                <fullName>Deployment</fullName>
                <color>#78C953</color>
                <label>Deployment</label>
            </value>
            <value>
                <fullName>Validate</fullName>
                <color>#E27001</color>
                <label>Validate</label>
            </value>
            <value>
                <fullName>Retrieve</fullName>
                <color>#A845DC</color>
                <label>Retrieve</label>
            </value>
            <value>
                <fullName>Rollback (Validate)</fullName>
            </value>
            <value>
                <fullName>Rollback (Deployment)</fullName>
            </value>
            <value>
                <fullName>Schedule Deployment</fullName>
            </value>
            <value>
                <fullName>Test Execution</fullName>
            </value>
            <value>
                <fullName>Test Execution Job</fullName>
            </value>
            <value>
                <fullName>Clean Org Data</fullName>
            </value>
            <value>
                <fullName>Install Vlocity Initial</fullName>
            </value>
            <value>
                <fullName>Pack Retry (Heroku)</fullName>
            </value>
            <value>
                <fullName>Tracking Organization - Retrieve</fullName>
            </value>
            <value>
                <fullName>AccelQ</fullName>
            </value>
            <value>
                <fullName>Veeva Rollback (Deployment)</fullName>
            </value>
            <value>
                <fullName>Veeva Deployment</fullName>
            </value>
            <value>
                <fullName>Pause</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Metadata_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Partial Completed</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Did Not Run</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Metadata_Log__c/fields/Succeed__c.field-meta.xml
<CustomField>
    <fullName>Succeed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Show if the job process completed with success or error</description>
    <label>Succeed?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Metadata_Log__c/fields/Success_Log__c.field-meta.xml
<CustomField>
    <fullName>Success_Log__c</fullName>
    <label>Success Log</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Organisation__c/Organisation__c.object-meta.xml
<CustomObject>
    <label>Org</label>
    <nameField>
        <label>Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orgs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PipelineStep__c/PipelineStep__c.object-meta.xml
<CustomObject>
    <label>PipelineStep</label>
    <nameField>
        <displayFormat>PSt-{0000}</displayFormat>
        <label>PipelineStep Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PipelineSteps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PipelineStep__c/fields/Peer_Review_Options__c.field-meta.xml
<CustomField>
    <fullName>Peer_Review_Options__c</fullName>
    <label>Peer Review Options</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Pull_Request__c/Pull_Request__c.object-meta.xml
<CustomObject>
    <label>Peer Review</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Peer Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pull_Request__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Peer Reviews</relationshipLabel>
    <relationshipName>Pull_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pull_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT( Approval_Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pull_Request_Reviewer__c/Pull_Request_Reviewer__c.object-meta.xml
<CustomObject>
    <label>Peer Reviewer</label>
    <nameField>
        <displayFormat>PRR-{000000}</displayFormat>
        <label>Peer Reviewer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Peer Reviewers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pull_Request_Reviewer__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <formula>Pull_Request__r.Branch__r.Branch_Name__c</formula>
    <label>Branch</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pull_Request_Reviewer__c/fields/Pull_Request__c.field-meta.xml
<CustomField>
    <fullName>Pull_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Peer Review</label>
    <referenceTo>Pull_Request__c</referenceTo>
    <relationshipLabel>Peer Reviewers</relationshipLabel>
    <relationshipName>Pull_Request_Reviewers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pull_Request_Reviewer__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Repository__c/Repository__c.object-meta.xml
<CustomObject>
    <label>Repository</label>
    <nameField>
        <label>Repository Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repositories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Repository__c/fields/Repository_Type__c.field-meta.xml
<CustomField>
    <fullName>Repository_Type__c</fullName>
    <label>Repository Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Vlocity</fullName>
            </value>
            <value>
                <fullName>Veeva Vault</fullName>
            </value>
            <value>
                <fullName>Commerce Cloud</fullName>
            </value>
            <value>
                <fullName>Marketing Cloud</fullName>
            </value>
            <value>
                <fullName>MuleSoft</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MetadataLogScheduler.cls
public with sharing class MetadataLogScheduler implements Schedulable, Database.AllowsCallouts {
    private Id userId;
    private String lastMetadataLogId;
    private Boolean isContinue;
    private Set<String> supportedProcessType = new Set<String>{
        FlosumConstants.PROCESS_AUTOMATION_STEP,
        FlosumConstants.PROCESS_PEER_REVIEW,
        FlosumConstants.PROCESS_DEPLOYMENT,
        FlosumConstants.PROCESS_ROLLBACK,
        FlosumConstants.PROCESS_VALIDATE
    };
    private Set<String> agentProcessType = new Set<String>{
        FlosumConstants.PROCESS_DEPLOYMENT,
        FlosumConstants.PROCESS_ROLLBACK,
        FlosumConstants.PROCESS_VALIDATE
    };

    private List<MetadataLogWrapper> metadataLogsList = new List<MetadataLogWrapper>();

    private static final String SAVE_BACKUP_ZIP = 'SAVE_BACKUP_ZIP';
    private static final String GET_TESTS = 'GET_TESTS';
    private static final String ERROR = 'ERROR';
    private static final String SAVE_DEPLOY_ZIP = 'SAVE_DEPLOY_ZIP';
    private static final String DEPLOY = 'DEPLOY';

    public MetadataLogScheduler(Id userId) {
        this.userId = userId;
        this.lastMetadataLogId = null;
        this.isContinue = false;
    }

    public MetadataLogScheduler(Id userId, String lastMetadataLogId, Boolean isContinue) {
        this.userId = userId;
        this.lastMetadataLogId = lastMetadataLogId;
        this.isContinue = isContinue;
    }
    public void execute(SchedulableContext sc) {
        Boolean isContinueProcessing = false;
        List<Metadata_Log__c> metadataLogRecords = new List<Metadata_Log__c>();
        if (this.lastMetadataLogId != null) {
            metadataLogRecords = [
                SELECT
                    Id,
                    Job_Completed__c,
                    Succeed__c,
                    Status__c,
                    Branch__c,
                    Start_Date__c,
                    PipelineStepId__c,
                    CreatedDate,
                    Metadata_Types__c,
                    Automation_Completed__c,
                    CreatedById,
                    Process_Type__c,
                    Options__c,
                    Async_Request_Id__c,
                    Organisation__c,
                    Success_Log__c,
                    Error_Log__c,
                    PipelineStepId__r.Peer_Review_Options__c,
                    PipelineStepId__r.Options__c,
                    PipelineStepId__r.Automation_Type__c
                FROM Metadata_Log__c
                WHERE
                    CreatedById = :userId
                    AND Process_Type__c IN :supportedProcessType
                    AND PipelineStepId__c != NULL
                    AND Job_Completed__c = FALSE
                    AND Status__c = :FlosumConstants.STATUS_IN_PROGRESS
                    AND Id > :this.lastMetadataLogId
                WITH SECURITY_ENFORCED
                ORDER BY Id
                LIMIT 4
            ];
        } else {
            metadataLogRecords = [
                SELECT
                    Id,
                    Job_Completed__c,
                    Succeed__c,
                    Status__c,
                    Branch__c,
                    Start_Date__c,
                    PipelineStepId__c,
                    CreatedDate,
                    Metadata_Types__c,
                    Automation_Completed__c,
                    CreatedById,
                    Process_Type__c,
                    Options__c,
                    Async_Request_Id__c,
                    Organisation__c,
                    Success_Log__c,
                    Error_Log__c,
                    PipelineStepId__r.Peer_Review_Options__c,
                    PipelineStepId__r.Options__c,
                    PipelineStepId__r.Automation_Type__c
                FROM Metadata_Log__c
                WHERE
                    CreatedById = :userId
                    AND Process_Type__c IN :supportedProcessType
                    AND PipelineStepId__c != NULL
                    AND Job_Completed__c = FALSE
                    AND Status__c = :FlosumConstants.STATUS_IN_PROGRESS
                WITH SECURITY_ENFORCED
                ORDER BY Id
                LIMIT 4
            ];
        }

        if (metadataLogRecords.size() == 4) {
            isContinueProcessing = true;
            this.lastMetadataLogId = metadataLogRecords.get(3).Id;
        }

        Map<Id, List<Pull_Request_Reviewer__c>> pullRequestReviewerMap = new Map<Id, List<Pull_Request_Reviewer__c>>();
        Map<Id, Boolean> moveForwardPermissionMap = new Map<Id, Boolean>();
        Set<String> pullRequestIds = new Set<String>();
        Set<String> branchIds = new Set<String>();
        List<Metadata_Log__c> agentUpdateMetadataLogs = new List<Metadata_Log__c>();

        if (!metadataLogRecords.isEmpty()) {
            for (Metadata_Log__c metadataLog : metadataLogRecords) {
                if (metadataLog.Process_Type__c == FlosumConstants.PROCESS_PEER_REVIEW) {
                    branchIds.add(metadataLog.Branch__c);
                    pullRequestIds.add(metadataLog.Metadata_Types__c);
                }
            }
            for (Pull_Request_Reviewer__c pullRequestReviewer : [
                SELECT Id, Status__c, Pull_Request__c
                FROM Pull_Request_Reviewer__c
                WHERE Pull_Request__c IN :pullRequestIds AND (Status__c = 'Reject' OR Status__c = 'Approved')
                WITH SECURITY_ENFORCED
            ]) {
                if (pullRequestReviewerMap.containsKey(pullRequestReviewer.Pull_Request__c)) {
                    pullRequestReviewerMap.get(pullRequestReviewer.Pull_Request__c).add(pullRequestReviewer);
                } else {
                    List<Pull_Request_Reviewer__c> newListRequestReviewers = new List<Pull_Request_Reviewer__c>();
                    newListRequestReviewers.add(pullRequestReviewer);
                    pullRequestReviewerMap.put(pullRequestReviewer.Pull_Request__c, newListRequestReviewers);
                }
            }
            for (String branch : branchIds) {
                moveForwardPermissionMap.put(
                    branch,
                    MetadataUtils.allowUserToMoveForwardFromBranch(
                            branch,
                            FlosumConstants.PullRequestAddToDeploymentType
                        )
                        .isSuccess
                );
            }
            for (Metadata_Log__c metadataLog : metadataLogRecords) {
                Datetime startDateTime = metadataLog.Start_Date__c != null
                    ? metadataLog.Start_Date__c
                    : metadataLog.CreatedDate;
                if (metadataLog.Process_Type__c == FlosumConstants.PROCESS_PEER_REVIEW) {
                    List<Pull_Request_Reviewer__c> listReviewers = pullRequestReviewerMap.get(
                        metadataLog.Metadata_Types__c
                    );
                    Boolean isRejectReview = false;
                    Boolean isApproveReview = false;
                    if (pullRequestReviewerMap.get(metadataLog.Metadata_Types__c) != null) {
                        for (Pull_Request_Reviewer__c pullRequestReviewer : listReviewers) {
                            if (pullRequestReviewer.Status__c == 'Reject') {
                                isRejectReview = true;
                            }
                            if (pullRequestReviewer.Status__c == 'Approved') {
                                isApproveReview = true;
                            }
                        }
                    }

                    if (isRejectReview) {
                        this.metadataLogsList.add(
                            new MetadataLogWrapper(
                                metadataLog,
                                false,
                                'Selected user has rejected the peer review for this branch. Please address any issues raised and submit for peer review again.'
                            )
                        );
                    } else {
                        if (moveForwardPermissionMap.get(metadataLog.Branch__c) && isApproveReview) {
                            this.metadataLogsList.add(new MetadataLogWrapper(metadataLog, true, ''));
                        } else {
                            if (String.isNotBlank(metadataLog.PipelineStepId__r.Peer_Review_Options__c)) {
                                Model.PeerReviewOptions peerReviewOptionsObj = new Model.PeerReviewOptions();
                                peerReviewOptionsObj = (Model.PeerReviewOptions) JSON.deserialize(
                                    metadataLog.PipelineStepId__r.Peer_Review_Options__c,
                                    Model.PeerReviewOptions.class
                                );
                                if (
                                    System.now() >
                                    startDateTime.addDays(Integer.valueOf(peerReviewOptionsObj.estimateDays))
                                ) {
                                    this.metadataLogsList.add(
                                        new MetadataLogWrapper(
                                            metadataLog,
                                            false,
                                            'This Peer Review took more than ' +
                                                peerReviewOptionsObj.estimateDays +
                                                ' days.'
                                        )
                                    );
                                } else {
                                    this.isContinue = true;
                                }
                            } else {
                                this.metadataLogsList.add(
                                    new MetadataLogWrapper(
                                        metadataLog,
                                        false,
                                        'This Peer Review does not have estimate options.'
                                    )
                                );
                            }
                        }
                    }
                } else if (metadataLog.Process_Type__c == FlosumConstants.PROCESS_AUTOMATION_STEP) {
                    if (metadataLog.Automation_Completed__c) {
                        this.metadataLogsList.add(new MetadataLogWrapper(metadataLog, metadataLog.Succeed__c, ''));
                    } else {
                        if (String.isNotBlank(metadataLog.PipelineStepId__r.Options__c)) {
                            Model.AutomationOptions automationObj = new Model.AutomationOptions();
                            automationObj = (Model.AutomationOptions) JSON.deserialize(
                                metadataLog.PipelineStepId__r.Options__c,
                                Model.AutomationOptions.class
                            );
                            if (metadataLog.PipelineStepId__r.Automation_Type__c == 'Flosum Scan') {
                                startCheckingStatusFlosumScan(
                                    metadataLog.Branch__c,
                                    metadataLog.Id,
                                    automationObj.isQualityGate,
                                    automationObj.isTakeResultFlosumScan == null
                                        ? false
                                        : automationObj.isTakeResultFlosumScan,
                                    automationObj.flosumScanBugs,
                                    automationObj.flosumScanVulnerabilities,
                                    automationObj.flosumScanCodeSmells,
                                    automationObj.flosumScanBugsSeverity,
                                    automationObj.flosumScanVulnerabilitiesSeverity,
                                    automationObj.flosumScanCodeSmellsSeverity
                                );
                            }
                            Integer countPeriod = Integer.valueOf(automationObj.estimate.substringBefore(' '));
                            String typePeriod = automationObj.estimate.substringAfter(' ');
                            if (typePeriod.startsWith('day')) {
                                if (System.now() > startDateTime.addDays(countPeriod)) {
                                    this.metadataLogsList.add(
                                        new MetadataLogWrapper(
                                            metadataLog,
                                            false,
                                            'This Automation Step took more than ' +
                                                countPeriod +
                                                ' ' +
                                                typePeriod +
                                                '.'
                                        )
                                    );
                                } else {
                                    this.isContinue = true;
                                }
                            } else {
                                if (System.now() > startDateTime.addHours(countPeriod)) {
                                    this.metadataLogsList.add(
                                        new MetadataLogWrapper(
                                            metadataLog,
                                            false,
                                            'This Automation Step took more than ' +
                                                countPeriod +
                                                ' ' +
                                                typePeriod +
                                                '.'
                                        )
                                    );
                                } else {
                                    this.isContinue = true;
                                }
                            }
                        } else {
                            this.metadataLogsList.add(
                                new MetadataLogWrapper(
                                    metadataLog,
                                    false,
                                    'This Automation Step does not have estimate options.'
                                )
                            );
                        }
                    }
                } else if (
                    agentProcessType.contains(metadataLog.Process_Type__c) &&
                    metadataLog.Automation_Completed__c == false
                ) {
                    if (System.now() > startDateTime.addDays(2)) {
                        this.metadataLogsList.add(
                            new MetadataLogWrapper(
                                metadataLog,
                                false,
                                'This ' + metadataLog.Process_Type__c + ' took more than 2 days.'
                            )
                        );
                    } else {
                        MetadataUtils.Options opt = (MetadataUtils.Options) System.JSON.deserialize(
                            metadataLog.Options__c,
                            MetadataUtils.Options.class
                        );
                        if (opt != null && opt.isAgentPipeline != null && opt.isAgentPipeline == true) {
                            if (metadataLog.Success_Log__c == SAVE_BACKUP_ZIP) {
                                metadataLog.Success_Log__c = '';
                                agentUpdateMetadataLogs.add(metadataLog);
                                startSentToFlosumAgent(SAVE_BACKUP_ZIP, metadataLog.Id, '');
                                this.isContinue = true;
                            } else if (metadataLog.Success_Log__c == GET_TESTS) {
                                metadataLog.Success_Log__c = '';
                                agentUpdateMetadataLogs.add(metadataLog);
                                startSentToFlosumAgent(GET_TESTS, metadataLog.Id, '');
                                this.isContinue = true;
                            } else if (metadataLog.Success_Log__c == SAVE_DEPLOY_ZIP) {
                                if (opt.ids != null) {
                                    startSentToFlosumAgent(SAVE_DEPLOY_ZIP, metadataLog.Id, opt.ids);
                                    this.isContinue = true;
                                } else {
                                    this.metadataLogsList.add(
                                        new MetadataLogWrapper(
                                            metadataLog,
                                            false,
                                            'The Agent did not return the attachment deployment Id.'
                                        )
                                    );
                                }
                                metadataLog.Success_Log__c = '';
                                agentUpdateMetadataLogs.add(metadataLog);
                            } else if (metadataLog.Success_Log__c == DEPLOY) {
                                if (metadataLog.Async_Request_Id__c != null) {
                                    Datetime sysTime = System.now().addSeconds(25);
                                    String chronExpression =
                                        '' +
                                        sysTime.second() +
                                        ' ' +
                                        sysTime.minute() +
                                        ' ' +
                                        sysTime.hour() +
                                        ' ' +
                                        sysTime.day() +
                                        ' ' +
                                        sysTime.month() +
                                        ' ? ' +
                                        sysTime.year();
                                    List<String> unknownErrorInDeploy = new List<String>();
                                    System.schedule(
                                        'Self MergeDeploymentCheckStatusScheduled ' + sysTime.getTime(),
                                        chronExpression,
                                        new MetadataDeployController(
                                            metadataLog.Branch__c,
                                            metadataLog.Organisation__c,
                                            metadataLog.Id,
                                            'CHECK STATUS',
                                            unknownErrorInDeploy,
                                            null
                                        )
                                    );
                                    metadataLog.Automation_Completed__c = true;
                                    metadataLog.Success_Log__c = '';
                                    agentUpdateMetadataLogs.add(metadataLog);
                                } else {
                                    this.metadataLogsList.add(
                                        new MetadataLogWrapper(
                                            metadataLog,
                                            false,
                                            'The Agent did not return the deployment request Id.'
                                        )
                                    );
                                }
                            } else if (metadataLog.Success_Log__c == ERROR) {
                                metadataLog.Success_Log__c = '';
                                agentUpdateMetadataLogs.add(metadataLog);
                                this.metadataLogsList.add(
                                    new MetadataLogWrapper(metadataLog, false, metadataLog.Error_Log__c)
                                );
                            } else {
                                this.isContinue = true;
                            }
                        }
                    }
                }
            }
        }

        List<Metadata_Log__c> logsForUpdate = new List<Metadata_Log__c>();
        List<Attachment> errorAttachments = new List<Attachment>();
        for (MetadataLogWrapper metaWrapper : this.metadataLogsList) {
            metaWrapper.metadataLog.Job_Completed__c = true;
            metaWrapper.metadataLog.Succeed__c = metaWrapper.isSuccess;
            metaWrapper.metadataLog.Status__c = FlosumConstants.STATUS_COMPLETED;
            metaWrapper.metadataLog.Completed_Date__c = Datetime.now();
            logsForUpdate.add(metaWrapper.metadataLog);
            if (!metaWrapper.isSuccess && metaWrapper.message != '') {
                Attachment attError = new Attachment(
                    ParentId = metaWrapper.metadataLog.Id, // attach error log to metadata log
                    Name = metaWrapper.metadataLog.Process_Type__c + ' Error Log',
                    Body = Blob.valueOf('ERROR: ' + metaWrapper.message),
                    ContentType = 'text/plain'
                );
                errorAttachments.add(attError);
            }
        }
        if (!logsForUpdate.isEmpty()) {
            DatabaseUtils.updateRecords(
                logsForUpdate,
                new List<Schema.DescribeFieldResult>{
                    Metadata_Log__c.Job_Completed__c.getDescribe(),
                    Metadata_Log__c.Status__c.getDescribe(),
                    Metadata_Log__c.Completed_Date__c.getDescribe(),
                    Metadata_Log__c.Succeed__c.getDescribe()
                }
            );
        }
        if (!agentUpdateMetadataLogs.isEmpty()) {
            DatabaseUtils.updateRecords(
                agentUpdateMetadataLogs,
                new List<Schema.DescribeFieldResult>{
                    Metadata_Log__c.Automation_Completed__c.getDescribe(),
                    Metadata_Log__c.Success_Log__c.getDescribe()
                }
            );
        }
        if (!errorAttachments.isEmpty()) {
            DatabaseUtils.insertRecords(
                errorAttachments,
                new List<Schema.DescribeFieldResult>{
                    Attachment.ParentId.getDescribe(),
                    Attachment.Name.getDescribe(),
                    Attachment.Body.getDescribe(),
                    Attachment.ContentType.getDescribe()
                }
            );
        }

        System.abortJob(sc.getTriggerId());
        if (isContinueProcessing) {
            Datetime sysTime = System.now().addSeconds(20);
            String cronExpression = String.format(
                FlosumConstants.CRON_EXPRESSION_TEMPLATE,
                new List<Integer>{
                    sysTime.second(),
                    sysTime.minute(),
                    sysTime.hour(),
                    sysTime.day(),
                    sysTime.month(),
                    sysTime.year()
                }
            );
            System.schedule(
                'MetadataLogScheduler' + this.userId,
                cronExpression,
                new MetadataLogScheduler(this.userId, this.lastMetadataLogId, this.isContinue)
            );
        } else if (this.isContinue) {
            Datetime sysTime = System.now().addMinutes(1);
            String cronExpression = String.format(
                FlosumConstants.CRON_EXPRESSION_TEMPLATE,
                new List<Integer>{
                    sysTime.second(),
                    sysTime.minute(),
                    sysTime.hour(),
                    sysTime.day(),
                    sysTime.month(),
                    sysTime.year()
                }
            );
            System.schedule(
                'MetadataLogScheduler' + this.userId,
                cronExpression,
                new MetadataLogScheduler(this.userId)
            );
        }
    }
    @future(callout=true)
    public static void startSentToFlosumAgent(String operation, String metadataLogId, String attachmentId) {
        if (operation == SAVE_BACKUP_ZIP) {
            MetadataUtils.checkTestClassesPipeline(metadataLogId);
        } else if (operation == GET_TESTS) {
            MetadataUtils.checkEnvVarPipeline(metadataLogId);
        } else if (operation == SAVE_DEPLOY_ZIP) {
            MetadataUtils.sentDeployZipToFlosumAgent(metadataLogId, attachmentId, '');
        }
    }

    @future(callout=true)
    public static void startCheckingStatusFlosumScan(
        Id branchId,
        Id metadataLogId,
        Boolean isQualityGate,
        Boolean isTakeResultFlosumScan,
        String flosumScanBugs,
        String flosumScanVulnerabilities,
        String flosumScanCodeSmells,
        String flosumScanBugsSeverity,
        String flosumScanVulnerabilitiesSeverity,
        String flosumScanCodeSmellsSeverity
    ) {
        Map<String, String> result = new Map<String, String>();

        try {
            BaseIntegration integration = (BaseIntegration) Type.forName(
                    AbstractAuthentication.FLOSUM_SCAN_PACKAGE_PREFIX,
                    'AnalyseBranchIntegration'
                )
                .newInstance();
            Map<String, Object> parameters = new Map<String, Object>{
                'branchId' => branchId,
                'metadataLogId' => metadataLogId,
                'bugs' => getSeverityList(flosumScanBugsSeverity),
                'vulnerabilities' => getSeverityList(flosumScanVulnerabilitiesSeverity),
                'codeSmells' => getSeverityList(flosumScanCodeSmellsSeverity)
            };
            result = (Map<String, String>) integration.getResult(parameters);
        } catch (Exception e) {
            System.debug(e.getMessage());
        }

        if (result != null) {
            List<Metadata_Log__c> metadataLogRecord = [
                SELECT Id, Branch__c, Succeed__c, Automation_Completed__c
                FROM Metadata_Log__c
                WHERE Id = :metadataLogId
                WITH SECURITY_ENFORCED
                LIMIT 1
            ];
            if (isTakeResultFlosumScan) {
                if (result.isEmpty() || result.get('resultBugs') == 'null' || result.get('resultBugs') == null) {
                    String resultExecute;
                    try {
                        BaseIntegration integrationExecute = (BaseIntegration) Type.forName(
                                AbstractAuthentication.FLOSUM_SCAN_PACKAGE_PREFIX,
                                'AnalyseBranchIntegration'
                            )
                            .newInstance();
                        resultExecute = (String) integrationExecute.execute(branchId);
                        if (
                            resultExecute == FlosumConstants.NOT_SELECTED_TYPES ||
                            resultExecute == FlosumConstants.NOT_COMPONENTS_IN_BRANCH
                        ) {
                            metadataLogRecord[0].Succeed__c = true;
                            metadataLogRecord[0].Automation_Completed__c = true;
                            DatabaseUtils.updateRecord(
                                metadataLogRecord[0],
                                new List<Schema.DescribeFieldResult>{
                                    Metadata_Log__c.Automation_Completed__c.getDescribe(),
                                    Metadata_Log__c.Succeed__c.getDescribe()
                                }
                            );
                            createLog(metadataLogRecord[0].Id, 'Flosum Scan Log', resultExecute);
                        }
                    } catch (Exception e) {
                        System.debug(e.getMessage());
                        metadataLogRecord[0].Succeed__c = false;
                        metadataLogRecord[0].Automation_Completed__c = true;
                        DatabaseUtils.updateRecord(
                            metadataLogRecord[0],
                            new List<Schema.DescribeFieldResult>{
                                Metadata_Log__c.Automation_Completed__c.getDescribe(),
                                Metadata_Log__c.Succeed__c.getDescribe()
                            }
                        );
                        createLog(metadataLogRecord[0].Id, 'Flosum Scan Error Log', 'Error: ' + e.getMessage());
                    }
                } else {
                    processResult(
                        result,
                        metadataLogRecord[0],
                        isQualityGate,
                        flosumScanBugs,
                        flosumScanVulnerabilities,
                        flosumScanCodeSmells
                    );
                }
            } else {
                processResult(
                    result,
                    metadataLogRecord[0],
                    isQualityGate,
                    flosumScanBugs,
                    flosumScanVulnerabilities,
                    flosumScanCodeSmells
                );
            }
        }
    }

    public static void processResult(
        Map<String, String> result,
        Metadata_Log__c metadataLog,
        Boolean isQualityGate,
        String flosumScanBugs,
        String flosumScanVulnerabilities,
        String flosumScanCodeSmells
    ) {
        Boolean isSuccess = false;
        String message = '';
        if (isQualityGate) {
            String resultQualityGate = result.get('qualityGateStatus');
            if (String.isNotEmpty(resultQualityGate) && resultQualityGate != 'ERROR') {
                isSuccess = true;
                message = 'The Flosum Scan Quality Gate result: ' + result.get('qualityGateStatus');
            } else {
                String newReliability = result.get('new_reliability_rating') != null
                    ? '\nReliability rating: ' + result.get('new_reliability_rating')
                    : '';
                String newSecurity = result.get('new_security_rating') != null
                    ? '\nSecurity rating: ' + result.get('new_security_rating')
                    : '';
                String newMaintainability = result.get('new_maintainability_rating') != null
                    ? '\nMaintainability rating: ' + result.get('new_maintainability_rating')
                    : '';
                String newCoverage = result.get('new_coverage') != null
                    ? '\nCoverage: ' + result.get('new_coverage')
                    : '';
                String newDuplicated = result.get('new_duplicated_lines_density') != null
                    ? '\nDuplicated lines density: ' + result.get('new_duplicated_lines_density')
                    : '';
                String newSecurityHotspots = result.get('new_security_hotspots_reviewed') != null
                    ? '\nSecurity hotspots reviewed: ' + result.get('new_security_hotspots_reviewed')
                    : '';
                message =
                    'The Flosum Scan result does not match the Quality Gate.' +
                    '\nQuality Gate Status: ' +
                    result.get('qualityGateStatus') +
                    newReliability +
                    newSecurity +
                    newMaintainability +
                    newCoverage +
                    newDuplicated +
                    newSecurityHotspots;
            }
        } else {
            isSuccess =
                isSuccessResult(flosumScanBugs, result.get('resultBugs')) &&
                isSuccessResult(flosumScanVulnerabilities, result.get('resultVulnerability')) &&
                isSuccessResult(flosumScanCodeSmells, result.get('resultCodeSmell'));
            if (!isSuccess) {
                message =
                    'The Flosum Scan result does not match the specified parameters:\n' +
                    'Bugs: ' +
                    result.get('resultBugs') +
                    '.\nVulnerabilities: ' +
                    result.get('resultVulnerability') +
                    '.\nCode Smells: ' +
                    result.get('resultCodeSmell');
            } else {
                message =
                    'The Flosum Scan result:\n' +
                    'Bugs: ' +
                    result.get('resultBugs') +
                    '.\nVulnerabilities: ' +
                    result.get('resultVulnerability') +
                    '.\nCode Smells: ' +
                    result.get('resultCodeSmell');
            }
        }
        try {
            Integer countIssues = 0;
            if (String.isNotBlank(result.get('resultBugs'))) {
                countIssues += Integer.valueOf(result.get('resultBugs'));
            }
            if (String.isNotBlank(result.get('resultVulnerability'))) {
                countIssues += Integer.valueOf(result.get('resultVulnerability'));
            }
            if (String.isNotBlank(result.get('resultCodeSmell'))) {
                countIssues += Integer.valueOf(result.get('resultCodeSmell'));
            }
            List<Branch__c> branches = [
                SELECT Id, Branch_Name__c, Repository__c, Repository_Type__c, Repository__r.Name
                FROM Branch__c
                WHERE Id = :metadataLog.Branch__c
                WITH SECURITY_ENFORCED
                LIMIT 1
            ];

            Map<String, String> properties = new Map<String, String>{
                'type' => 'Flosum Scan',
                'trigger_source' => 'Pipeline',
                'count_issues' => !isQualityGate ? String.valueOf(countIssues) : '',
                'result' => isSuccess ? 'Success' : 'Failed',
                'branch_id' => branches.get(0).Id,
                'branch_name' => branches.get(0).Branch_Name__c,
                'repository_id' => branches.get(0).Repository__c,
                'repository_name' => branches.get(0).Repository__r.Name,
                'repository_type' => String.isNotBlank(branches.get(0).Repository_Type__c)
                    ? branches.get(0).Repository_Type__c
                    : 'Metadata'
            };

            List<AnalyticsService.AnalyticsEvent> events = new List<AnalyticsService.AnalyticsEvent>();
            AnalyticsService.AnalyticsEvent event = new AnalyticsService.AnalyticsEvent('Code Scan', properties);
            events.add(event);
            AnalyticsService.scheduleAnalytics(events);
        } catch (Exception e) {
        }

        metadataLog.Succeed__c = isSuccess;
        metadataLog.Automation_Completed__c = true;
        DatabaseUtils.updateRecord(
            metadataLog,
            new List<Schema.DescribeFieldResult>{
                Metadata_Log__c.Automation_Completed__c.getDescribe(),
                Metadata_Log__c.Succeed__c.getDescribe()
            }
        );
        if (!isSuccess) {
            createLog(metadataLog.Id, 'Flosum Scan Error Log', message);
        } else {
            createLog(metadataLog.Id, 'Flosum Scan Log', message);
        }
    }

    public static String getSeverityList(String severity) {
        List<String> severityList = new List<String>();
        if (String.isNotBlank(severity)) {
            List<String> severityTypeList = new List<String>{ 'Info', 'Minor', 'Major', 'Critical', 'Blocker' };
            Integer indexSeverity = severityTypeList.indexOf(severity);
            for (Integer indexKey = indexSeverity; indexKey < severityTypeList.size(); indexKey++) {
                severityList.add(severityTypeList.get(indexKey).toUpperCase());
            }
        } else {
            severityList.add('INFO');
        }

        return String.join(severityList, ',');
    }

    public static Boolean isSuccessResult(String limitValue, String resultValue) {
        if (String.isBlank(limitValue)) {
            return true;
        }
        if (
            String.isNotBlank(resultValue) &&
            String.isNotBlank(limitValue) &&
            Integer.valueOf(resultValue) <= Integer.valueOf(limitValue)
        ) {
            return true;
        }
        return false;
    }

    public static void createLog(Id metadataLogId, String name, String message) {
        Attachment att = new Attachment(
            ParentId = metadataLogId, // attach error log to metadata log
            Name = name,
            Body = Blob.valueOf(message),
            ContentType = 'text/plain'
        );
        DatabaseUtils.insertRecord(
            att,
            new List<Schema.DescribeFieldResult>{
                Attachment.ParentId.getDescribe(),
                Attachment.Name.getDescribe(),
                Attachment.Body.getDescribe(),
                Attachment.ContentType.getDescribe()
            }
        );
    }

    @JsonAccess(serializable='always' deserializable='always')
    public class MetadataLogWrapper {
        public Metadata_Log__c metadataLog;
        public String message;
        public Boolean isSuccess;

        public MetadataLogWrapper(Metadata_Log__c metadataLog, Boolean isSuccess, String msg) {
            this.metadataLog = metadataLog;
            this.message = msg;
            this.isSuccess = isSuccess;
        }
    }
}