force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Branch Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch Lookup</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Branch__c.RecordType.Id</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <infoMessage>Select a record type</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Branches</relationshipLabel>
    <relationshipName>Branches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Branch__c/fields/Branch_Description__c.field-meta.xml
<CustomField>
    <fullName>Branch_Description__c</fullName>
    <label>Branch Description</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Branch__c/fields/Branch_Name__c.field-meta.xml
<CustomField>
    <fullName>Branch_Name__c</fullName>
    <label>Branch Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Branch__c/fields/Enforce_pull_request__c.field-meta.xml
<CustomField>
    <fullName>Enforce_pull_request__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Enforce Peer Review at Branch</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Branch__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
                <default>true</default>
                <label>In Progress</label>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Branch__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.Id</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Branches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Metadata_Log__c/Metadata_Log__c.object-meta.xml
<CustomObject>
    <label>Metadata Log</label>
    <nameField>
        <displayFormat>ML-{YYYY}-{MM}-{DD}-{0000}</displayFormat>
        <label>Metadata Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metadata Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Metadata_Log__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Metadata Logs</relationshipLabel>
    <relationshipName>Metadata_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Metadata_Log__c/fields/Job_Completed__c.field-meta.xml
<CustomField>
    <fullName>Job_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Show if the process related to deployment or retrieve has been completed or not for the current  Async request Id</description>
    <label>Job Completed?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Metadata_Log__c/fields/Metadata_Types__c.field-meta.xml
<CustomField>
    <fullName>Metadata_Types__c</fullName>
    <label>Metadata Types</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Metadata_Log__c/fields/Options__c.field-meta.xml
<CustomField>
    <fullName>Options__c</fullName>
    <description>Other options for deployment/validation</description>
    <label>Options</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Metadata_Log__c/fields/PipelineStepId__c.field-meta.xml
<CustomField>
    <fullName>PipelineStepId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>PipelineStepId</label>
    <referenceTo>PipelineStep__c</referenceTo>
    <relationshipLabel>Metadata Logs</relationshipLabel>
    <relationshipName>Metadata_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Metadata_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Partial Completed</fullName>
            </value>
            <value>
                <fullName>Not Started</fullName>
            </value>
            <value>
                <fullName>Did Not Run</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Metadata_Log__c/fields/Succeed__c.field-meta.xml
<CustomField>
    <fullName>Succeed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Show if the job process completed with success or error</description>
    <label>Succeed?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PipelineStep__c/PipelineStep__c.object-meta.xml
<CustomObject>
    <label>PipelineStep</label>
    <nameField>
        <displayFormat>PSt-{0000}</displayFormat>
        <label>PipelineStep Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PipelineSteps</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PipelineStep__c/fields/Peer_Review_Options__c.field-meta.xml
<CustomField>
    <fullName>Peer_Review_Options__c</fullName>
    <label>Peer Review Options</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Pull_Request__c/Pull_Request__c.object-meta.xml
<CustomObject>
    <label>Peer Review</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Peer Reviews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pull_Request__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pull_Request__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Peer Reviews</relationshipLabel>
    <relationshipName>Pull_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pull_Request__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <inlineHelpText>This is our latest field for Description and has a limit of 131,072 characters.</inlineHelpText>
    <label>Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Pull_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT( Approval_Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pull_Request_Reviewer__c/Pull_Request_Reviewer__c.object-meta.xml
<CustomObject>
    <label>Peer Reviewer</label>
    <nameField>
        <displayFormat>PRR-{000000}</displayFormat>
        <label>Peer Reviewer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Peer Reviewers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pull_Request_Reviewer__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <formula>TEXT( Status__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Approval Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pull_Request_Reviewer__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <formula>Pull_Request__r.Branch__r.Branch_Name__c</formula>
    <label>Branch</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pull_Request_Reviewer__c/fields/Pull_Request__c.field-meta.xml
<CustomField>
    <fullName>Pull_Request__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Peer Review</label>
    <referenceTo>Pull_Request__c</referenceTo>
    <relationshipLabel>Peer Reviewers</relationshipLabel>
    <relationshipName>Pull_Request_Reviewers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pull_Request_Reviewer__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Pull_Request_Reviewer__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reviewer</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Pull_Request_Reviewers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pull_Request_Setting__c/Pull_Request_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Peer Review Setting</label>
</CustomObject>

force-app/main/default/objects/Pull_Request_Setting__c/fields/AddToDeploymentApprovalType__c.field-meta.xml
<CustomField>
    <fullName>AddToDeploymentApprovalType__c</fullName>
    <label>AddToDeploymentApprovalType</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pull_Request_Setting__c/fields/DeploymentPercentageORNumberOfUsers__c.field-meta.xml
<CustomField>
    <fullName>DeploymentPercentageORNumberOfUsers__c</fullName>
    <label>DeploymentPercentageORNumberOfUsers</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Pull_Request_Setting__c/fields/PullRequestDeploymentSetting__c.field-meta.xml
<CustomField>
    <fullName>PullRequestDeploymentSetting__c</fullName>
    <defaultValue>false</defaultValue>
    <label>PeerReviewDeploymentSetting</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SchedulePeerReview.cls
public with sharing class SchedulePeerReview implements Schedulable {
    private Id metadataLogId;

    public SchedulePeerReview(Id metadataLogId) {
        this.metadataLogId = metadataLogId;
    }
    public void execute(SchedulableContext sc) {
        String descriptionPeerReview = '';
        String userGroupsPeerReview = '';
        List<String> idsReviewers = new List<String>();
        Set<Id> userIdSet = new Set<Id>();
        String branchId = '';
        String branchName = '';
        String branchDescription = '';

        List<Metadata_Log__c> metadataLogRecords = [
            SELECT
                PipelineStepId__c,
                Job_Completed__c,
                Succeed__c,
                Status__c,
                Options__c,
                Branch__c,
                Branch__r.Branch_Name__c,
                Branch__r.Branch_Description__c,
                Branch__r.Enforce_pull_request__c,
                Metadata_Types__c
            FROM Metadata_Log__c
            WHERE Id = :metadataLogId
            WITH SECURITY_ENFORCED
            LIMIT 1
        ];
        if (!metadataLogRecords.isEmpty() && !String.isEmpty(metadataLogRecords[0].Branch__c)) {
            branchId = metadataLogRecords[0].Branch__c;
            branchName = metadataLogRecords[0].Branch__r.Branch_Name__c;
            branchDescription = String.isEmpty(metadataLogRecords[0].Branch__r.Branch_Description__c)
                ? ''
                : metadataLogRecords[0].Branch__r.Branch_Description__c;
            List<PipelineStep__c> pipelineStepList = [
                SELECT Id, Peer_Review_Options__c
                FROM PipelineStep__c
                WHERE Id = :metadataLogRecords[0].PipelineStepId__c
                WITH SECURITY_ENFORCED
                LIMIT 1
            ];
            if (!pipelineStepList.isEmpty() && String.isNotBlank(pipelineStepList[0].Peer_Review_Options__c)) {
                try {
                    Model.PeerReviewOptions peerReviewOptionsObj = new Model.PeerReviewOptions();
                    peerReviewOptionsObj = (Model.PeerReviewOptions) JSON.deserialize(
                        pipelineStepList[0].Peer_Review_Options__c,
                        Model.PeerReviewOptions.class
                    );
                    descriptionPeerReview = peerReviewOptionsObj.description;
                    userGroupsPeerReview = peerReviewOptionsObj.userGroups;
                    idsReviewers = peerReviewOptionsObj.idsReviewers;
                    if (userGroupsPeerReview == 'User') {
                        Integer index = idsReviewers.indexOf(UserInfo.getUserId());
                        if (index != -1) {
                            idsReviewers.remove(index);
                        }
                        userIdSet = verifyUsers(idsReviewers);
                    } else {
                        List<String> userFromGroup = new List<String>();
                        for (User userInGroup : [
                            SELECT Id
                            FROM User
                            WHERE Id IN (SELECT UserOrGroupId FROM GroupMember WHERE Group.Id IN :idsReviewers)
                            WITH SECURITY_ENFORCED
                        ]) {
                            if (userInGroup.Id != UserInfo.getUserId()) {
                                userFromGroup.add(userInGroup.Id);
                            }
                        }
                        userIdSet = verifyUsers(userFromGroup);
                    }

                    Pull_Request__c pullRequest = new Pull_Request__c();
                    pullRequest.Branch__c = branchId;
                    pullRequest.Name = branchName.abbreviate(80);
                    pullRequest.Approval_Status__c = 'Pending';
                    pullRequest.Description__c = descriptionPeerReview;
                    Integer valueForNumberOfUsers = 0;

                    List<Pull_Request_Reviewer__c> ListOfPullRequestReviewer = new List<Pull_Request_Reviewer__c>();
                    List<Messaging.SingleEmailMessage> listOfmails = new List<Messaging.SingleEmailMessage>();
                    List<User> userinfList = [
                        SELECT Email, FirstName
                        FROM User
                        WHERE Id IN :userIdSet AND IsActive = TRUE
                        WITH SECURITY_ENFORCED
                    ];

                    Boolean isNeedMoreReviewers = false;

                    Pull_Request_Setting__c pullRequestSetting = (Pull_Request_Setting__c.getOrgDefaults() != null &&
                        Pull_Request_Setting__c.getOrgDefaults().Id != null)
                        ? Pull_Request_Setting__c.getOrgDefaults()
                        : new Pull_Request_Setting__c();
                    Boolean isDeploymentPeerReviewSettingEnabled =
                        pullRequestSetting.PullRequestDeploymentSetting__c &
                        metadataLogRecords[0].Branch__r.Enforce_pull_request__c;

                    if (
                        pullRequestSetting.AddToDeploymentApprovalType__c != null &&
                        pullRequestSetting.DeploymentPercentageORNumberOfUsers__c != null &&
                        pullRequestSetting.DeploymentPercentageORNumberOfUsers__c > 0 &&
                        isDeploymentPeerReviewSettingEnabled
                    ) {
                        String selectedMethodForPullRequest = pullRequestSetting.AddToDeploymentApprovalType__c;

                        if (selectedMethodForPullRequest == 'NoOfUsers') {
                            valueForNumberOfUsers = (Integer) pullRequestSetting.DeploymentPercentageORNumberOfUsers__c;
                            if (userinfList.size() < valueForNumberOfUsers) {
                                isNeedMoreReviewers = true;
                            }
                        }
                    }

                    List<CronTrigger> jobs = [
                        SELECT Id, CronJobDetail.Name, State
                        FROM CronTrigger
                        WHERE CronJobDetail.Name = :'MetadataLogScheduler' + UserInfo.getUserId()
                    ];

                    Datetime sysTime = System.now().addMinutes(1);
                    String cronExpression = String.format(
                        FlosumConstants.CRON_EXPRESSION_TEMPLATE,
                        new List<Integer>{
                            sysTime.second(),
                            sysTime.minute(),
                            sysTime.hour(),
                            sysTime.day(),
                            sysTime.month(),
                            sysTime.year()
                        }
                    );
                    if (jobs.isEmpty()) {
                        System.schedule(
                            'MetadataLogScheduler' + UserInfo.getUserId(),
                            cronExpression,
                            new MetadataLogScheduler(UserInfo.getUserId())
                        );
                    } else if (jobs[0].State == 'DELETED') {
                        System.abortJob(jobs[0].Id);
                        System.schedule(
                            'MetadataLogScheduler' + UserInfo.getUserId(),
                            cronExpression,
                            new MetadataLogScheduler(UserInfo.getUserId())
                        );
                    } else if (jobs[0].State == 'PAUSED') {
                        System.resumeJobById(jobs[0].Id);
                    }

                    //  Analytics
                    try {
                        List<AnalyticsService.AnalyticsEvent> events = new List<AnalyticsService.AnalyticsEvent>();
                        Map<String, String> properties = AnalyticsService.getBranchAnalyticsDetails(branchId);
                        properties.put('trigger_source', 'Pipeline');
                        properties.put('count_of_selected_users', String.valueOf(userinfList.size()));
                        AnalyticsService.AnalyticsEvent event = new AnalyticsService.AnalyticsEvent('Peer Review Create', properties);
                        events.add(event);
                        if (Limits.getQueueableJobs() >= 1) {
                            AnalyticsService.scheduleAnalytics(events);
                        } else {
                            System.enqueueJob(new AnalyticsQueueable(events));
                        }
                    } catch (Exception e){}

                    DatabaseUtils.insertRecord(
                        pullRequest,
                        new List<Schema.DescribeFieldResult>{
                            Pull_Request__c.Branch__c.getDescribe(),
                            Pull_Request__c.Name.getDescribe(),
                            Pull_Request__c.Approval_Status__c.getDescribe(),
                            Pull_Request__c.Description__c.getDescribe(),
                            Pull_Request__c.Approval_Status__c.getDescribe()
                        }
                    );

                    metadataLogRecords[0].Metadata_Types__c = pullRequest.Id;
                    metadataLogRecords[0].Status__c = FlosumConstants.STATUS_IN_PROGRESS;
                    metadataLogRecords[0].Start_Date__c = Datetime.now();
                    DatabaseUtils.updateRecord(
                        metadataLogRecords[0],
                        new List<Schema.DescribeFieldResult>{
                            Metadata_Log__c.Metadata_Types__c.getDescribe(),
                            Metadata_Log__c.Status__c.getDescribe(),
                            Metadata_Log__c.Start_Date__c.getDescribe()
                        }
                    );

                    for (User userInf : userinfList) {
                        //Add PullRequestReviewer
                        ListOfPullRequestReviewer.add(
                            new Pull_Request_Reviewer__c(
                                User__c = userInf.Id,
                                Status__c = 'Pending',
                                Pull_Request__c = pullRequest.Id
                            )
                        );
                    }

                    if (isNeedMoreReviewers) {
                        List<EmailTemplate> emailTemplateLi = [
                            SELECT Id, Name, DeveloperName, NamespacePrefix
                            FROM EmailTemplate
                            WHERE
                                DeveloperName = 'AddMoreReviewers'
                                AND NamespacePrefix = :FlosumConstants.getNameSpacePrefix()
                            WITH SECURITY_ENFORCED
                            LIMIT 1
                        ];
                        if (!emailTemplateLi.isEmpty()) {
                            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                            if (FlosumConstants.getOrgWideEmailAddress() != null) {
                                mail.setOrgWideEmailAddressId(FlosumConstants.getOrgWideEmailAddress());
                            }
                            mail.setTemplateId(emailTemplateLi[0].Id);
                            mail.setTargetObjectId(UserInfo.getUserId());
                            mail.setSaveAsActivity(false);
                            mail.setWhatId(pullRequest.Id);
                            listOfmails.add(mail);
                        }
                    }

                    if (!ListOfPullRequestReviewer.isEmpty()) {
                        DatabaseUtils.insertRecords(
                            ListOfPullRequestReviewer,
                            new List<Schema.DescribeFieldResult>{
                                Pull_Request_Reviewer__c.User__c.getDescribe(),
                                Pull_Request_Reviewer__c.Status__c.getDescribe(),
                                Pull_Request_Reviewer__c.Pull_Request__c.getDescribe()
                            }
                        );
                    }

                    if (!Test.isRunningTest() && !listOfmails.isEmpty()) {
                        Messaging.sendEmail(listOfmails);
                    }

                    BranchActivityController.createPullRequestLog(pullRequest.Id);
                } catch (Exception e) {
                    completeMetadataLog(metadataLogRecords[0], 'Completed', false);
                    createErrorLog(metadataLogRecords[0], e.getMessage());
                }
            }
        }
        System.abortJob(sc.getTriggerId());
    }

    public static Set<Id> verifyUsers(List<String> usersIds) {

        Set<Id> userList = new Set<Id>();
        Set<Id> verifiedUserList = new Set<Id>();
        Set<Id> permissionSetIds = new Set<Id>();
        String apiName = FlosumConstants.Approve_Reject_Pull_Request;
        String strNameSpace = FlosumConstants.getNameSpacePrefix();

        for (SetupEntityAccess access : [
            SELECT ParentId
            FROM SetupEntityAccess
            WHERE
                SetupEntityId IN (
                    SELECT Id
                    FROM CustomPermission
                    WHERE DeveloperName = :apiName AND NamespacePrefix = :strNameSpace
                )
        ]) {
            permissionSetIds.add(access.ParentId);
        }

        if (strNameSpace != '') {
            for (User ur : [
                SELECT Name, Username
                FROM User
                WHERE Id IN (
                        SELECT AssigneeId
                        FROM PermissionSetAssignment
                        WHERE PermissionSetId IN :permissionSetIds
                    )
                    AND Id IN (
                        SELECT UserId
                        FROM UserPackageLicense
                        WHERE PackageLicense.NamespacePrefix = :strNameSpace
                    )
                LIMIT 1000
            ]) {
                userList.add(ur.Id);
            }
        } else {
            for (User ur : [
                SELECT Name, Username
                FROM User
                WHERE Id IN (
                        SELECT AssigneeId
                        FROM PermissionSetAssignment
                        WHERE PermissionSetId IN :permissionSetIds
                    )
                LIMIT 1000
            ]) {
                userList.add(ur.Id);
            }
        }
        for (String userId : usersIds) {
            if (userList.contains(userId)) {
                verifiedUserList.add(userId);
            }
        }
        return verifiedUserList;
    }

    public static void completeMetadataLog(Metadata_Log__c metadataLog, String status, Boolean isSucceed) {
        metadataLog.Job_Completed__c = true;
        metadataLog.Succeed__c = isSucceed;
        metadataLog.Status__c = status;
        metadataLog.Completed_Date__c = Datetime.now();
        DatabaseUtils.updateRecord(
            metadataLog,
            new List<Schema.DescribeFieldResult>{
                Metadata_Log__c.Job_Completed__c.getDescribe(),
                Metadata_Log__c.Status__c.getDescribe(),
                Metadata_Log__c.Completed_Date__c.getDescribe(),
                Metadata_Log__c.Succeed__c.getDescribe()
            }
        );
    }

    public static void createErrorLog(Metadata_Log__c metadataLog, String errorMessage) {
        Attachment attError = new Attachment(
            ParentId = metadataLog.Id, // attach error log to metadata log
            Name = 'Peer Review Error Log',
            Body = Blob.valueOf('ERROR: ' + errorMessage),
            ContentType = 'text/plain'
        );
        DatabaseUtils.insertRecord(
            attError,
            new List<Schema.DescribeFieldResult>{
                Attachment.ParentId.getDescribe(),
                Attachment.Name.getDescribe(),
                Attachment.Body.getDescribe(),
                Attachment.ContentType.getDescribe()
            }
        );
    }
}