force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Branch Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch Lookup</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Branch__c.RecordType.Id</field>
            <operation>notEqual</operation>
            <value></value>
        </filterItems>
        <infoMessage>Select a record type</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Branches</relationshipLabel>
    <relationshipName>Branches</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Metadata_Log__c/Metadata_Log__c.object-meta.xml
<CustomObject>
    <label>Metadata Log</label>
    <nameField>
        <displayFormat>ML-{YYYY}-{MM}-{DD}-{0000}</displayFormat>
        <label>Metadata Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metadata Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Metadata_Log__c/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Metadata Logs</relationshipLabel>
    <relationshipName>Metadata_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Metadata_Log__c/fields/Job_Completed__c.field-meta.xml
<CustomField>
    <fullName>Job_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Show if the process related to deployment or retrieve has been completed or not for the current  Async request Id</description>
    <label>Job Completed?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Metadata_Log__c/fields/Organisation__c.field-meta.xml
<CustomField>
    <fullName>Organisation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization</label>
    <referenceTo>Organisation__c</referenceTo>
    <relationshipLabel>Metadata Logs</relationshipLabel>
    <relationshipName>Metadata_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Metadata_Log__c/fields/Patch__c.field-meta.xml
<CustomField>
    <fullName>Patch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deployment</label>
    <referenceTo>Patch__c</referenceTo>
    <relationshipLabel>Metadata Logs</relationshipLabel>
    <relationshipName>Metadata_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Metadata_Log__c/fields/Process_Type__c.field-meta.xml
<CustomField>
    <fullName>Process_Type__c</fullName>
    <description>Determine the process for which the log has been created</description>
    <label>Process Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Patch</fullName>
                <color>#0B6FCE</color>
                <label>Patch</label>
            </value>
            <value>
                <fullName>Deployment</fullName>
                <color>#78C953</color>
                <label>Deployment</label>
            </value>
            <value>
                <fullName>Validate</fullName>
                <color>#E27001</color>
                <label>Validate</label>
            </value>
            <value>
                <fullName>Retrieve</fullName>
                <color>#A845DC</color>
                <label>Retrieve</label>
            </value>
            <value>
                <fullName>Rollback (Validate)</fullName>
            </value>
            <value>
                <fullName>Rollback (Deployment)</fullName>
            </value>
            <value>
                <fullName>Schedule Deployment</fullName>
            </value>
            <value>
                <fullName>Test Execution</fullName>
            </value>
            <value>
                <fullName>Test Execution Job</fullName>
            </value>
            <value>
                <fullName>Clean Org Data</fullName>
            </value>
            <value>
                <fullName>Install Vlocity Initial</fullName>
            </value>
            <value>
                <fullName>Pack Retry (Heroku)</fullName>
            </value>
            <value>
                <fullName>Tracking Organization - Retrieve</fullName>
            </value>
            <value>
                <fullName>AccelQ</fullName>
            </value>
            <value>
                <fullName>Veeva Rollback (Deployment)</fullName>
            </value>
            <value>
                <fullName>Veeva Deployment</fullName>
            </value>
            <value>
                <fullName>Pause</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Metadata_Log__c/fields/Succeed__c.field-meta.xml
<CustomField>
    <fullName>Succeed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Show if the job process completed with success or error</description>
    <label>Succeed?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Organisation__c/Organisation__c.object-meta.xml
<CustomObject>
    <label>Org</label>
    <nameField>
        <label>Organization Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orgs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Patch__c/Patch__c.object-meta.xml
<CustomObject>
    <label>Deployment</label>
    <nameField>
        <label>Deployment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deployments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DeploymentDataForPath.cls
public with sharing class DeploymentDataForPath {
    @AuraEnabled
    public static String deploymentOrgData(String recordId, String obj) {
        List<MetadataLogsWrapper> metaLogWrap = new List<MetadataLogsWrapper>();
        if (String.isBlank(recordId)) {
            return null;
        }

        List<Metadata_Log__c> metadataLogData = new List<Metadata_Log__c>();
        if (obj != null && obj == 'branch') {
            metadataLogData = [
                SELECT Organisation__r.Name, Job_Completed__c, Succeed__c
                FROM Metadata_Log__c
                WHERE
                    Branch__c = :recordId
                    AND (Process_Type__c = :FlosumConstants.PROCESS_DEPLOYMENT
                    OR Process_Type__c = :FlosumConstants.PROCESS_SCHEDULED_DEPLOYMENT
                    OR Process_Type__c = :B2CConstants.PROCESS_STRING_MAP.get(B2CConstants.Process.DEPLOY_BRANCH)
                    OR Process_Type__c = :MCConstants.DEPLOY_TYPE
                    OR Process_Type__c = :FlosumConstants.PROCESS_ROLLBACK)
                WITH SECURITY_ENFORCED
                ORDER BY CreatedDate DESC, Name DESC
                LIMIT 10
            ];
        } else {
            metadataLogData = [
                SELECT Organisation__r.Name, Job_Completed__c, Succeed__c
                FROM Metadata_Log__c
                WHERE
                    Patch__c = :recordId
                    AND (Process_Type__c = :FlosumConstants.PROCESS_DEPLOYMENT
                    OR Process_Type__c = :FlosumConstants.PROCESS_SCHEDULED_DEPLOYMENT
                    OR Process_Type__c = :FlosumConstants.PROCESS_ROLLBACK)
                WITH SECURITY_ENFORCED
                ORDER BY CreatedDate DESC, Name DESC
                LIMIT 10
            ];
        }

        // Changes in SOQL and FOR are related to display only 10 latest path components
        for (Integer i = metadataLogData.size() - 1; i >= 0; i--) {
        //for(Metadata_Log__c metaLogData : metadataLogData){
            metaLogWrap.add(
                new MetadataLogsWrapper(
                    metadataLogData[i].Organisation__r.Name,
                    metadataLogData[i].Job_Completed__c,
                    metadataLogData[i].Succeed__c
                )
            );
        }
        return JSON.serialize(metaLogWrap);
    }

    public class MetadataLogsWrapper {
        public String name;
        public Boolean jobComp;
        public Boolean jobSucceed;
        public MetadataLogsWrapper(String name, Boolean jobComp, Boolean jobSucceed) {
            this.name = name;
            this.jobComp = jobComp;
            this.jobSucceed = jobSucceed;
        }
    }
}